/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/$callback'
import { Route as protectedtravelPlanRouteImport } from './routes/(protected)/(travel)/plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/$callback',
  path: '/auth/$callback',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedtravelPlanRoute = protectedtravelPlanRouteImport.update({
  id: '/(protected)/(travel)/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/$callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/plan': typeof protectedtravelPlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/$callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/plan': typeof protectedtravelPlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/$callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/(protected)/(travel)/plan': typeof protectedtravelPlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/$callback' | '/auth/login' | '/plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/$callback' | '/auth/login' | '/plan'
  id:
    | '__root__'
    | '/'
    | '/auth/$callback'
    | '/auth/login'
    | '/(protected)/(travel)/plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  protectedtravelPlanRoute: typeof protectedtravelPlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$callback': {
      id: '/auth/$callback'
      path: '/auth/$callback'
      fullPath: '/auth/$callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/(travel)/plan': {
      id: '/(protected)/(travel)/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof protectedtravelPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  protectedtravelPlanRoute: protectedtravelPlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
